---

- hosts: all
  become: true
  tasks:
  - name: update and upgrade the servers
    yum:
      update_cache: yes
      upgrade: yes
  - name: install httpd
    tags: apache, httpd
    yum:
      name:
        - httpd
      state: latest 
  - name: set timezone to Africa/Lagos
    tags: time
    timezone: name=Africa/Lagos
  - name: print hostname on server
    tags: printf
    shell: echo "<h1>This is my server name $(hostname -f)</h1>" > /var/www/html/index.html
  - name: restart httpd
    tags: restart
    service:
      name: httpd
      state: restarted